meta_product_name: "Développeur web à Bordeaux - Maxime Oudin"
meta_title: "Développeur web à Bordeaux - Maxime Oudin"
meta_description: "Développeur web à Bordeaux - Maxime Oudin spécialisé dans le développement web Ruby on Rails"
meta_image: "yellow_logo.svg"